language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
# Dependencies
install: 
    - "pip install ."
    - "pip install -r requirements.txt"
    - "pip install pytest-cov"
    - "pip install coveralls"
# Test command
script: 
    py.test --cov easycython tests/
after_success:
    coveralls
