language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
install:
    - "pip install ."
    - "pip install -r requirements.txt"
    - "pip install pytest-cov"
    - "pip install coveralls"
script:
    py.test --cov easycython tests/
after_success:
    coveralls
