environment:
  PYDIR: "C:\\Python"

  matrix:
      #    - PYTHON_VERSION: "2.6"

    - PYTHON_VERSION: "2.7"

      #    - PYTHON_VERSION: "3.0"

      #    - PYTHON_VERSION: "3.1"

      #    - PYTHON_VERSION: "3.2"

      #    - PYTHON_VERSION: "3.3"

      #    - PYTHON_VERSION: "3.4"

platform:
    #  - x86
  - x64

init:
  - "ECHO %PYDIR% %PYTHON_VERSION%"

install:
  - "appveyor/install.cmd"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "appveyor/runtests.cmd"

after_test:
  - "appveyor/buildwheels.cmd"
  - ps: "ls dist"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
